name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cleanup Space
        uses: rokibhasansagar/slimhub_actions@main

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
